config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :ratings, :defaults => { :format => :json }, only: [:create]
  post 'movie-search', to: 'movies#search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true

  belongs_to :user
  has_many :list_movies
  has_many :movies, through: :list_movies
end

app/models/list_movie.rb
class ListMovie < ApplicationRecord
  belongs_to :list
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :ratings
  has_many :list_movies
  has_many :lists, through: :list_movies
  after_create :add_imdb_data

  def add_imdb_data
    downcased_movie_hash = {}
    movie = IMDBService.new.get_movie(imdbID)
    movie.each_pair { |k,v| downcased_movie_hash.merge!(k.downcase => v) }
    downcased_movie_hash.select! {|k,v| Movie.column_names.include?(k)}
    self.update_attributes(downcased_movie_hash)
  end

  def user_rating(user_id)
    ratings.where(user_id: user_id)[0]
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :recoverable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :lists
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    lists_path
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.where(user: current_user)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # POST /lists
  # POST /lists.json
  def create
    list_movies = params.delete("movie_ids").split(",")
    params[:list][:movie_ids] = list_movies
    @list = List.new(list_params)
    @list.user = current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title,movie_ids: [])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /movies-search
  def search
    movies = IMDBService.new.search(params[:search_string])
    @results = movies["Search"].map do |movie|
      Movie.find_or_create_by(imdbID: movie["imdbID"])
    end

    respond_to do |format|
      format.js {render layout: false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :poster, :genre)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    if Rating.exists?({:user_id => rating_params[:user_id], :movie_id => rating_params[:movie_id]})
      @rating = Rating.find_by_user_id_and_movie_id(rating_params[:user_id], rating_params[:movie_id])
      @rating.score = rating_params[:score]
    else
      @rating = Rating.create(rating_params)
    end

    head :ok
  end

  def rating_params
    params.require(:rating).permit(:score, :user_id, :movie_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-danger'
    when 'alert' then 'alert alert-danger'
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def avg_rating(list)
    ratings = []
    list.movies.each do |movie|
      potential_rating = movie.ratings.where(user_id: current_user.id)
      ratings << potential_rating[0].score unless potential_rating.empty?
    end
    ratings.empty? ? 'No User Ratings' : (ratings.inject { |sum, el| sum + el }.to_f / ratings.size).round(2)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to "Mr. Movie Manager", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
      <li class="nav-item">
        <%= link_to "My Lists", lists_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create List", new_list_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
    <div class="my-2 my-lg-0">
      <% if current_user %>
        <%= link_to "Log Out", destroy_user_session_path, class: "btn btn-outline-success my-2 my-sm-0", method: "DELETE" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %> alert-dismissible fade show">
          <%= value %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <%= hidden_field_tag 'movie_ids' %>
<% if list.errors.any? %>
  <% list.errors.full_messages.each do |message| %>
  <div class="alert alert-danger alert-dismissible fade show">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
<% end %>

<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title, id: :list_title, class: "form-control" %>
</div>

<div class="actions">
  <%= form.submit "Submit", class: "btn btn-primary" %>
</div>
<% end %>

app/views/lists/_list_short.html.erb
<div class="card short-list-container">
  <%= link_to list_path(list), class: "card-body" do %>
  <div class="row">
    <h4 class="col-sm"><%= list.title %></h3>
    <h4 class="col-sm">Average Rating: <%= avg_rating(list) %></h4>
    <h4 class="col-sm"># of Movies: <%= list.movies.count %></h4>
    <%= button_to "Delete", { action: "destroy", id: list.id }, method: :delete,
        class: "btn btn-danger col-sm", id: "list-#{list.id}" %>
  </div>
  <% end %>
</div>

<script>
$("#list-<%= list.id %>").click(function(event){
    event.stopPropagation();
    confirm("Are you sure?");
});
</script>

app/views/lists/index.html.erb
<h1>Your Lists</h1>
<% if @lists.empty? %>
  <h3>You don't have any lists yet <%= fa_icon "frown" %></h3>
<% else %>
  <% @lists.each do |list| %>
    <%= render partial: 'list_short', locals: {list: list} %>
  <% end %>
<% end %>
<br>

<%= link_to 'Make a New List', new_list_path, class: "btn btn-primary" %>

app/views/lists/new.html.erb
<div class="row">
  <h1>Create A New List</h1>
</div>
<div class="row">
  <div class="col-4">
    <%= render 'form', list: @list %>
    <br>
    <%= render 'movies/search_form' %>
    <br>
    <h4>Movies in your list</h4>
    <ul id="added-movies">
    </ul>
  </div>
  <div class="col-8" id="search-results"></div>
</div>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<% @list.movies.each do |movie| %>
  <%= render partial: 'movies/movie', locals: {movie: movie} %>
<% end %>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/movies/_movie.html.erb
<div class="card">
  <div class="row card-body">
    <div class="col-3">
      <% if movie.poster == "N/A" %>
      <div class="col-sm poster"><%= image_tag("stock-poster.png") %></div>
      <% else %>
      <div class="col-sm poster"><%= image_tag(movie.poster) %></div>
      <% end %>
    </div>
    <div class="col-3">
      <h3 class="col-sm"><%= movie.title %></h3>
      <% if movie.user_rating(current_user.id).nil? %>
        <%= render partial: 'ratings/create', locals: {rating: movie.ratings.build(:user => current_user, :movie => movie)} %>
      <% else %>
        <%= render partial: 'ratings/create', locals: {rating: movie.user_rating(current_user.id)} %>
      <% end %>
    </div>
    <div class="col-6">
      <p class="col-sm">Year: <%= movie.year %></p>
      <p class="col-sm">Genre: <%= movie.genre %></p>
      <p class="col-sm">Runtime: <%= movie.runtime %></p>
      <p class="col-sm">Director: <%= movie.director %></p>
      <p class="col-sm">Plot: <%= movie.plot %></p>
    </div>
  </div>
</div>

app/views/movies/_search_form.html.erb
<%= form_with url: movie_search_path do |f| %>
  <div class="form-group">
    <%= f.label :search_string, "Search for movies for your list:" %>
    <%= f.text_field :search_string, placeholder: "My Left Foot", class: "form-control" %>
  </div>
  <%= f.submit "Search", class: "btn btn-success" %>
<% end %>

app/views/movies/_search_index.html.erb
<div class="results-container">
  <% if results.empty? %>
  <h4>No results</h4>
  <% else %>
  <h2>Search Results <small id="searchHelp" class="form-text text-muted">Click a movie to add it to your list</small></h2>
  <div class="results-list">
    <% results.each do |movie| %>
      <%= render partial: 'search_result', locals: {movie: movie} %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/movies/_search_result.html.erb
<div class="card" id=<%= movie.id %>>
  <div class="row card-body">
    <div class="col-3">
      <% if movie.poster == "N/A" %>
        <div class="col-sm poster"><%= image_tag("stock-poster.png") %></div>
      <% else %>
        <div class="col-sm poster"><%= image_tag(movie.poster) %></div>
      <% end %>
    </div>
    <div class="col-9">
      <h3 class="col-sm"><%= movie.title %></h3>
      <p class="col-sm">Year: <%= movie.year %></p>
      <p class="col-sm">Genre: <%= movie.genre %></p>
      <p class="col-sm">Runtime: <%= movie.runtime %></p>
      <p class="col-sm">Director: <%= movie.director %></p>
    </div>
  </div>
</div>

<script>
  $("#"+<%= movie.id %>).click(function () {
    var movie_id_val = $('#movie_ids').val();
    var movie_id_arr = movie_id_val.split(',');
    var movie_id = $(this).attr('id');
    var _this = this;

    if (!$(this).hasClass("bg-success")) {
      $(this).addClass("bg-success", 1000, "easeOutBounce");
      $('#movie_ids').val(movie_id_val + movie_id + ",");
      $('#added-movies').append('<li id="movie-<%= movie.id %>"><%= movie.title %></li>');
    } else {
      $(this).removeClass("bg-success", 1000, "easeOutBounce");
      $('#added-movies > #movie-<%= movie.id %>').remove();
      // To remove element from aaray
      movie_id_arr = jQuery.grep(movie_id_arr, function (n) {
        return n == $(_this).attr("id")
      });
      $('#movie_ids').val(movie_id_arr.join(','));
    }
  });
</script>

app/views/movies/movie_search.js.erb
$('#search-results').html("<%= escape_javascript(render partial: 'search_index', locals: { results: @results } ) %>");

app/views/movies/search.js.erb
$('#search-results').html("<%= escape_javascript(render partial: 'search_index', locals: { results: @results } ) %>");

app/views/ratings/_create.html.erb
<% id = Random.rand(1000) %>
<div id="star-rating-<%= id %>" data-score=<%= rating.score %>></div>
<script>
$('#star-rating-<%= id %>').raty({
  path: '/assets/',
  number: 10,
  click: function(score, evt) {
    $.post({
      url: "/ratings/",
      data: {
        rating: {
          user_id: <%= rating.user.id %>,
          movie_id: <%= rating.movie.id %>,
          score: score,
        }
      },
      dataType: "json"
    });
  }
})
</script>

app/views/welcome/index.html.erb
<div style="text-align:center">
  <h1>Welcome to Mr. Movie Manager</h1>
  <%= image_tag("mr-manager.gif", class: "centered") %>
  <h4>This app is your one stop shop for creating your own curated list of movies.</h4>
  <p>Create an account to get started</p>
  <%= link_to "Create Account", new_user_registration_path, class: "btn btn-success" %>
</div>